version: 2.1
jobs:
  build:
    docker:
      image: circleci/node
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: npm run build
workflows:
  build-and-deploy:
    jobs:
      - build